# Generated by Django 5.0.6 on 2024-06-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doacao", "0003_doacao_data_doacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doacao",
            old_name="data_doacao",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="doacao",
            old_name="valor_doado",
            new_name="valor",
        ),
    ]
