# Generated by Django 5.0.6 on 2024-06-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacao", "0004_rename_data_doacao_doacao_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
    ]
