# Generated by Django 5.0.6 on 2024-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doacao", "0005_alter_customuser_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="doacao",
            name="descricao",
            field=models.CharField(default="teste", max_length=100),
            preserve_default=False,
        ),
    ]
